version: '3.8'

networks:
  bunnyshell:
    driver: bridge

x-common-variables: &common-variables
  MYSQL_DATABASE: bunnyshell
  MYSQL_ROOT_PASSWORD: bunnyshell

services:
  app:
    build:
      args:
        user: ritwik
        uid: 1000
      context: ./server
      dockerfile: Dockerfile
    image: bunnyshell-server
    container_name: bunnyshell-api
    restart: unless-stopped
    ports:
      - "5000:5000"
    working_dir: /var/www
    volumes:
      - ./server:/var/www/
      - /var/www/node_modules
      - /var/www/vendor
    networks:
      - bunnyshell